apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-nameserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nameserver
  template:
    metadata:
      labels:
        app: nameserver
    spec:
      containers:
      - name: container-nameserver
        image: kuroseaist/rtm-nameserver:1.0
      nodeSelector:
        nameserver: "true"

---
apiVersion: v1
kind: Service
metadata:
  name: service-nameserver
spec:
  type: NodePort
  clusterIP: 10.96.0.100
  ports:
    - name: "nameserver-port"
      protocol: "TCP"
      port: 2809
      targetPort: 2809
      nodePort: 30289
  selector:
    app: nameserver

